In [1]:
import numpy as np

In [4]:
np.square(4)

16

In [5]:
4**2


16

In [6]:
np.sqrt(4)

2.0

In [12]:
arreglo1 = np.array([1,-2,3,-4,5])
arreglo2 = np.zeros(5)
compara = np.logical_and(arreglo1 > arreglo2, arreglo1 % 2 == 0)
print(compara)

[False False False False False]


In [16]:
compara = np.logical_and(arreglo1 > arreglo2, arreglo1 % 2 != 0)
print(compara)
print(arreglo1[compara])

[ True False  True False  True]
[1 3 5]


In [18]:
matriz = np.zeros([5,3])

In [19]:
matriz.size


15

In [20]:
matriz.shape

(5, 3)

In [2]:
notas = np.random.random([40,3])*6+1 #matriz con notas aleatorias
notas

array([[2.88991774, 6.6356288 , 5.33591063],
       [5.24434232, 6.83316558, 3.21745956],
       [1.29933846, 6.06304573, 6.76266628],
       [2.59754848, 5.70673975, 2.54392797],
       [5.08105295, 6.65802177, 2.00931825],
       [3.12973784, 6.32823414, 6.37826281],
       [2.99164799, 2.47173786, 6.25944184],
       [1.32641501, 1.81865636, 5.89687188],
       [6.70578595, 6.94256955, 6.71706378],
       [6.51662666, 6.28954296, 3.96240452],
       [3.65478363, 3.48209337, 4.90180902],
       [5.08489628, 1.87355116, 6.35637992],
       [2.010474  , 6.22878199, 3.15785505],
       [5.81010244, 2.59240917, 2.39015217],
       [1.30282216, 6.90509208, 2.64716482],
       [4.99190056, 3.57151328, 3.8005276 ],
       [2.26163391, 5.50200076, 6.16094266],
       [3.26559123, 5.3739417 , 3.1415892 ],
       [4.10137741, 3.03310834, 6.78599411],
       [1.74309315, 1.67989543, 5.05333898],
       [1.97908922, 5.8960654 , 5.03219742],
       [6.59773812, 5.02019239, 4.95633827],
       [5.

In [4]:
prom = np.zeros([40]) #arreglo para guardar los promedios
prom

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0.])

In [5]:
for i in range(0, notas.shape[0]):
  prom[i] = notas[i,:].mean()
  print(prom[i])

4.9538190537359865
5.0983224844965465
4.7083501557937035
3.6160720662359034
4.582797657348841
5.278744930321895
3.907609228171451
3.013981083062397
6.788473095437223
5.58952471264713
4.012895339885183
4.438275786728711
3.7990370159410376
3.597554595126121
3.618359686011941
4.121313810751083
4.641525778169738
3.9270407093961914
4.64015995195016
2.8254425199730284
4.302450678842377
5.524756259123682
4.2072584227501
3.2775387667800255
3.030189216346626
4.443532368949569
3.895158455037418
3.9023330496359647
4.325607222828001
4.734183440807121
3.327130488348818
3.297045213148588
4.557036364974122
4.436183433143399
2.549364553777217
3.4537901599077023
6.317224265807681
5.385426205751673
4.688373860588061
3.4110105630111343


In [10]:
print(f'Los promedios son {prom.round(2)}')

Los promedios son [4.95 5.1  4.71 3.62 4.58 5.28 3.91 3.01 6.79 5.59 4.01 4.44 3.8  3.6
 3.62 4.12 4.64 3.93 4.64 2.83 4.3  5.52 4.21 3.28 3.03 4.44 3.9  3.9
 4.33 4.73 3.33 3.3  4.56 4.44 2.55 3.45 6.32 5.39 4.69 3.41]


# **Resolución de Problemas Guía 5**
---

**Ejercicio 01**

In [17]:
arreglo = np.random.random(100)
arreglo

array([0.94417822, 0.23594734, 0.41435034, 0.83611876, 0.18738026,
       0.09825047, 0.21414294, 0.10783761, 0.90219205, 0.27978776,
       0.87023182, 0.75744589, 0.51129287, 0.25588608, 0.93550313,
       0.17795136, 0.86061372, 0.14688279, 0.42488552, 0.58035709,
       0.42973602, 0.60722199, 0.15014291, 0.84402964, 0.94718693,
       0.93060274, 0.23296018, 0.07133278, 0.37713232, 0.08922655,
       0.33995245, 0.96469379, 0.89010725, 0.76436499, 0.86147788,
       0.40388768, 0.82052639, 0.6517721 , 0.59752377, 0.97787446,
       0.28392634, 0.35607439, 0.3818774 , 0.20792468, 0.08112305,
       0.3678336 , 0.6918543 , 0.94057299, 0.05400591, 0.94698074,
       0.99328895, 0.42840349, 0.47345837, 0.50564964, 0.30871603,
       0.73520167, 0.46777062, 0.20461918, 0.9827915 , 0.47068164,
       0.19223681, 0.96231447, 0.9909327 , 0.1944376 , 0.49591531,
       0.87739263, 0.91640331, 0.40825538, 0.53138199, 0.80845828,
       0.83064272, 0.96848611, 0.27665648, 0.83968988, 0.50887

In [22]:
dif = 1 - arreglo.max()

In [27]:
arreglo_modificado = arreglo + dif
print(arreglo_modificado)

[0.95088927 0.24265839 0.42106139 0.84282982 0.19409131 0.10496152
 0.22085399 0.11454866 0.9089031  0.28649881 0.87694287 0.76415694
 0.51800392 0.26259713 0.94221418 0.18466242 0.86732477 0.15359384
 0.43159657 0.58706814 0.43644707 0.61393305 0.15685397 0.85074069
 0.95389799 0.93731379 0.23967123 0.07804383 0.38384337 0.0959376
 0.3466635  0.97140485 0.8968183  0.77107604 0.86818893 0.41059873
 0.82723745 0.65848316 0.60423482 0.98458551 0.29063739 0.36278544
 0.38858845 0.21463573 0.0878341  0.37454465 0.69856535 0.94728405
 0.06071696 0.9536918  1.         0.43511454 0.48016942 0.51236069
 0.31542708 0.74191272 0.47448167 0.21133023 0.98950255 0.47739269
 0.19894786 0.96902553 0.99764376 0.20114866 0.50262636 0.88410369
 0.92311437 0.41496643 0.53809304 0.81516933 0.83735377 0.97519716
 0.28336754 0.84640093 0.51558387 0.87797209 0.16848149 0.95772037
 0.03631635 0.73788903 0.68642849 0.77235209 0.41884278 0.62567019
 0.6146932  0.89819705 0.03526153 0.02137688 0.66699913 0.64409

**Ejercicio 02**

In [51]:
arreglo_02 = np.random.random([100])
arreglo_02

array([9.47825053e-04, 1.15011106e-01, 4.93029442e-01, 8.75108052e-02,
       7.12744253e-01, 4.06144866e-01, 1.97080610e-01, 5.10017433e-01,
       8.01268091e-01, 5.34946847e-02, 3.71833758e-01, 8.75723772e-01,
       7.41093744e-01, 3.92897429e-01, 1.30988902e-01, 9.69313135e-01,
       2.84455580e-01, 1.28273398e-01, 1.00474489e-02, 3.29943015e-01,
       7.84595502e-01, 9.11191880e-01, 1.80316813e-01, 2.06172087e-01,
       1.29768836e-01, 9.22610513e-01, 2.85148098e-01, 3.62958864e-01,
       5.57498863e-01, 1.55641823e-01, 7.20138769e-01, 4.32928629e-01,
       7.15823498e-01, 6.73973428e-03, 9.47966858e-01, 9.44716439e-01,
       9.65960333e-01, 6.52025338e-01, 9.37831519e-01, 2.56250984e-01,
       8.82465388e-01, 7.73109145e-01, 7.34456888e-01, 9.40631952e-01,
       6.46395166e-01, 2.98251053e-01, 2.83225290e-01, 7.87417974e-01,
       1.96053918e-01, 3.42646642e-01, 5.68347761e-02, 2.75435442e-01,
       5.69211944e-01, 4.92714579e-01, 2.61944831e-01, 1.29384007e-01,
      

In [55]:
promedio_inicial = np.mean(arreglo_02)
promedio_inicial

0.4978669654659214

In [64]:
nuevo_arreglo = arreglo_02 - promedio_inicial
nuevo_arreglo

array([-4.96919140e-01, -3.82855860e-01, -4.83752339e-03, -4.10356160e-01,
        2.14877287e-01, -9.17220992e-02, -3.00786356e-01,  1.21504677e-02,
        3.03401126e-01, -4.44372281e-01, -1.26033208e-01,  3.77856807e-01,
        2.43226779e-01, -1.04969536e-01, -3.66878063e-01,  4.71446170e-01,
       -2.13411385e-01, -3.69593568e-01, -4.87819517e-01, -1.67923950e-01,
        2.86728536e-01,  4.13324915e-01, -3.17550152e-01, -2.91694878e-01,
       -3.68098130e-01,  4.24743548e-01, -2.12718867e-01, -1.34908102e-01,
        5.96318971e-02, -3.42225143e-01,  2.22271804e-01, -6.49383363e-02,
        2.17956532e-01, -4.91127231e-01,  4.50099892e-01,  4.46849473e-01,
        4.68093367e-01,  1.54158372e-01,  4.39964554e-01, -2.41615981e-01,
        3.84598423e-01,  2.75242180e-01,  2.36589923e-01,  4.42764987e-01,
        1.48528200e-01, -1.99615913e-01, -2.14641675e-01,  2.89551009e-01,
       -3.01813047e-01, -1.55220323e-01, -4.41032189e-01, -2.22431524e-01,
        7.13449783e-02, -

In [70]:
print(f'Los número menores a 0 son {np.sum(nuevo_arreglo < 0)}')
print(f'Los número mayores a 0 son {np.sum(nuevo_arreglo > 0)}')

Los número menores a 0 son 51
Los número mayores a 0 son 49
